services:
  portainer:
    image: portainer/portainer-ce:latest
    hostname: portainer-server
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-db:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${HOST_NAME}`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt
      - traefik.http.services.portainer.loadBalancer.server.port=9000
volumes:
  portainer-db:
    name: portainer-db
networks:
  traefik-network:
    external: true
